name: "Multi event pipeline workflow" # namke of the pipeline
on:
  push: # Event: whenever a push is made to the repository on the master branch
    branches:
      - master # branch name
      - test

jobs:
    on-push: # job name
        runs-on: ubuntu-latest # the pipeline will run on the latest version of ubuntu
        steps: # steps to be executed in the job
          - name: "Running on master push" # name of the step
            run: echo "Running on master push" # command to be executed

              